# Generated by Django 5.2.9 on 2025-12-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
