# Generated by Django 5.2.9 on 2025-12-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0004_alter_student_account"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PRESENT", "Keldi"), ("ABSENT", "Kemagan")],
                        default="PRESENT",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Rejada"),
                            ("ACTIVE", "O'qiyapti"),
                            ("STOPPED", "To'tatilgan"),
                            ("GRATUATED", "Bititirgan"),
                            ("CANCELED", "Bekor qilingan"),
                        ],
                        default="PLANNED",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="groups", to="students.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="groups",
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
    ]
